---
fixtures:
  repositories:
    stdlib:
      ref: "4.24.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    nginx:
      ref: "v0.13.0"
      repo: "https://github.com/voxpupuli/puppet-nginx"
    apt:
      ref: "4.4.0"
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
    concat:
      ref: "3.0.0"
      repo: "https://github.com/puppetlabs/puppetlabs-concat"
  symlinks:
    vision_nginx: '#{source_dir}'
