---
fixtures:
  repositories:
    stdlib:
      ref: "v6.0.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    nginx:
      ref: "v1.0.0"
      repo: "https://github.com/voxpupuli/puppet-nginx"
    concat:
      ref: "v6.1.0"
      repo: "https://github.com/puppetlabs/puppetlabs-concat"
  symlinks:
    vision_nginx: '#{source_dir}'
