sudo: false
language: ruby
cache: bundler
rvm: 2.3.4
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  allow_failures:
    - env: STRICT_VARIABLES="yes" CHECK="rubocop"
      bundler_args: --without testing acceptance
  include:
    - env: STRICT_VARIABLES="yes" CHECK="rubocop"
      bundler_args: --without testing acceptance
    - env: STRICT_VARIABLES="yes" CHECK="lint"
      bundler_args: --without rubocop acceptance
    - env: STRICT_VARIABLES="yes" CHECK="validate"
      bundler_args: --without rubocop acceptance
    - env: STRICT_VARIABLES="yes" CHECK="spec"
      bundler_args: --without rubocop acceptance
    - env: STRICT_VARIABLES="yes" CHECK="beaker"
      bundler_args: --without rubocop
      services: docker
      sudo: required
    - env: STRICT_VARIABLES="yes" CHECK="beaker" BEAKER_set="debian9"
      bundler_args: --without rubocop
      services: docker
      sudo: required
notifications:
  email: false
  slack:
    secure: be8NGuUOtYwkeuAnAE7Fux7i5MckLra9bpfIAsHA5WsGBfUSYwBPHbbjWASCfZb7fP4hRlRgyfPF8ZI9wEgOgapOzWrX4wPJc162ppwDLnEISVGpbE4gVIapmZzdV5fwwYhHJf7eQva3Tt1cOkcxYL/43UMJu1kxOlLXOKzVNMmBv2Fi0dq2QJNTn8QqXQWdb4UhsEK2tC9b6Mlsg6kCijSZCgdOtGuS4704cLJGnaTrX7AVyz6mNu/Rj+bP3SIaVteK9OPlH0LtUZDMB+bEdzN8//5JiA/dfu1rDmbyyett75jEfLLmgnNlDFge8tfUwP/T3lML4LLgVNNRNFtztwowYCF4aOhU82vd5rcXLtCNDbBN4yW3eZ+HZ6Ja5XPRXZjRVkbf7BPYhCSnHMaxaQfL8fh2YFrP5EmZ8jey/+r8vI0UBQD6rjJgWUuG73UK1MuOJHEiOVOcJJTPzLX2fFSAqeHyP5Q71keLl2HAVqAiBk8gZxwoaThbD3m4t+DVV3EB10Kw8Ol3IRORwF/jReEsteiR/qigrXMFD0+2C3HRzM6MWNcnfywD0Jje5/DDY6MpxlW+llLIRJnEfN5p/g7gbOf6gLPDdAoDI9/dx0Ze29KdxO/hMAUWq4bOFBJ1OzYQFyRnTTZa50ywA7z8EPNp7w7dQwu1UznLXdeba3Y=
